.eslintrc.js
.github/workflows/pipeline.yml
.prettierignore
CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md
package-lock.json
package.json

This PR...
- Updates `CODE_OF_CONDUCT.md`
- Adds [Prettier](https://prettier.io/docs/en/install.html) as a dev dependency
- Adds a CI workflow
- Update files to use the Prettier code style

..add CI workflow

---

.github/workflows/pipeline.yml
package.json
src/altStudents/altStudentController.js
src/altStudents/passport.js
src/mentors/mentorController.js
src/model/alt-student.js
src/model/mentor.js
src/model/regular-student.js
src/students/passport.js
src/students/studentController.js
utils/authUtils.js

This PR...
- Updates ci scripts for formatting code with Prettier style

Update scripts for Prettier

---

app.js
package-lock.json
utils/errorHandler.js

This PR...
- Adds a function to handle errors

new: add "global" error handling function

---

README.md

This PR...
- the README.md file
-
- [ x ] updated the docs
Fixes #

docs:updated README.md with all-contibutors bot

---

README.md

This PR...
- the style of the markdown document

docs(style): format readme to enforce Prettier style

---

.eslintrc.js
package-lock.json
package.json
utils/errorHandler.js

This PR...
- adds and utilizes the [cross-env](https://www.npmjs.com/package/cross-env) package as a development dependency
- adds a script to run tests
- Surrender eslint indent rules to prettier code style ([Prettier vs. Linters](https://prettier.io/docs/en/comparison.html))

Update scripts for CI and testing

---

.github/workflows/pipeline.yml
middleware/validator.js
model/account.js
routes/index.js
src/auth/auth.js
src/auth/router.js
src/mentors/mentorController.js
src/mentors/route.js
utils/customError.js

This PR...
- updates password validation 
- modifies code base to pass tests defined in #30 
- failing test cases
Fixes #35

#35 - fix bugs and test fails

---

src/auth/__tests__/mentor.reg.test.js

This PR...
- update expected decoded token object
- update expected http status code for syntactically incorrect requests

Update/test: mentor registration

---

model/account.js

This PR...
- the Accounts model
- #59
Fixes #59

fix: change function to return account ref

---

src/auth/__tests__/logout.test.js
src/auth/auth.js
src/auth/router.js

This PR...
- test coverage for `/auth/logout` route
- implement logout
- #65 
- #66 
fixes #66, fixes #65

Feat: Logout

---

api-mentor.yaml
app.js
package-lock.json
package.json

docs: adds documentation for mentor routes

---

app.js
routes/index.js
src/docs/endpoints.yaml
src/docs/index.js

This PR...
- moves the documentation to its own module

Refactor documentation module

---

middleware/validator.js
model/validator.js
src/auth/router.js
src/mentors/route.js
src/student/studentRoute.js

This PR...
- moves validation schema to model and refactors validator middleware function
- #70

refactor: DRY validator middleware

---

src/docs/endpoints.yaml

This PR...
- update api responses
-
Fixes #

refactor: updated docs to included latest response messages

---

model/question.js
model/validator.js
routes/index.js
src/questions/__tests__/questions.test.js
src/questions/index.js
src/questions/questions.controller.js
src/questions/questions.service.js
src/questions/questions.validator.js
test/fixtures/questions.json
test/testHelper.js
test/testUtils.js
utils/errorHandler.js

This PR...
-
-
Fixes #73 🚀
🙏🏾 Join the discussion on #76

new: question component init

---

.all-contributorsrc
.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/feature.yml
CONTRIBUTING.md
LICENSE
README.md
app.js
src/docs/endpoints.yaml

This PR...
- StudyBuddy to AltCamp
-
Fixes #

chore: update project name [skip-ci]

---

README.md
src/docs/endpoints.yaml

This PR...
- the hostname in the API documentation
-
Fixes #

fix: correct hostname

---

.all-contributorsrc
.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/feature.yml
CONTRIBUTING.md
LICENSE
README.md
app.js
model/answer.js
src/answers/__tests__/answer.test.js
src/answers/answers.controller.js
src/answers/answers.service.js
src/docs/endpoints.yaml
src/questions/__tests__/questions.test.js
src/questions/index.js
src/questions/questions.controller.js
src/questions/questions.service.js
test/fixtures/answers.json
test/testHelper.js
test/testUtils.js

Answer module

---

model/answer.js
src/answers/__tests__/answer.test.js
src/answers/answers.controller.js
src/answers/answers.service.js
src/questions/index.js
test/fixtures/answers.json
test/testHelper.js
test/testUtils.js

Post and Update Answer

---

src/questions/questions.service.js

fix: include author details in operation response

---

src/auth/__tests__/mentor.reg.test.js
src/auth/__tests__/student.reg.test.js

test: update tests for registration

---

src/questions/questionsValidator.js

This PR...
- Question Validation
-
Fixes #

Question validation refactor

---

config/index.js
src/accounts/__tests__/profilePicture.test.js
src/accounts/accountsController.js
src/accounts/accountsService.js

- create seperate folders for live assets and test assets on cloudinary, 
- fix: error deleting file when there's no file to delete.

feat: upload profile picture

---

src/accounts/accountsController.js

ch: formatting

---

src/auth/__tests__/auth.mentor.reg.test.js
src/auth/__tests__/auth.student.reg.test.js

test: fix failing auth tests

---

constant/index.js
src/bookmarks/__tests__/bookmarks.test.js
src/bookmarks/bookmarksService.js
src/docs/endpoints.yaml
test/test.db.js
utils/db.js

fix: include slug for bookmarked answers

---

src/accounts/accountsService.js
src/bookmarks/bookmarksController.js
src/bookmarks/bookmarksService.js
src/common/apiFeatures.js
src/common/pagination/paginationSchema.js
src/posts/postsService.js
src/questions/questionsService.js

improve: add sorting/ordering to pagination

---

model/account.js
src/common/apiFeatures.js
src/common/pagination/paginationSchema.js

This PR...
- [new: index firstName and LastName fields](https://github.com/AltCamp/altcampv1-backend/commit/b80b11259409a283e7bbdf3a35b91a940d6a9469)
- [new: add search functionality for users](https://github.com/AltCamp/altcampv1-backend/commit/b56340f1083e3a9a52a8b2c0b7ce5973d9938d37)
Closes #187

[feature]: Search for users

---

app.js

fix: set allowed CORS origins

---

.github/workflows/deployToProduction.yml

ci: deploy to digital ocean

---

app.js
constant/index.js
middleware/authenticate.js
package-lock.json
package.json
src/answers/__tests__/answer.test.js
src/answers/index.js
src/comments/__tests__/comments.test.js
src/comments/index.js
src/posts/__tests__/posts.test.js
src/posts/index.js
src/questions/__tests__/questions.test.js
src/questions/index.js
test/fixtures/accounts.json
test/testUtils.js

This PR...
- Use `responseHandler` module to handle responses in authentication middlewares.
- Modify the `verifyUser` function to use `passport.authenticate` with a callback function. If the user is authenticated, the request proceeds to the next middleware; otherwise, an unauthorized response is returned.
- Add `authOptional` middleware to allow optional authentication. This middleware uses `passport.authenticate` without returning an error response if the user is not authenticated.
- Implement `authEmailIsVerified` middleware to verify if the user's email is verified before allowing access. If the user is authenticated and their email is verified, the request proceeds to the next middleware; otherwise, a forbidden response is returned.
Fixes #204

Restrict access/interaction for unverified users

---

model/answer.js
model/comment.js
model/post.js
model/question.js
model/schemas/index.js
src/questions/__tests__/questions.test.js

This PR...
- splits the schemas into separate smaller files in order to enhance code modularity and facilitate reusability.
This refactoring improves maintainability by allowing different combinations of schemas to be used for constructing models as needed.
Fixes #213

Improve Code Modularity and Reusability through Schema Refactoring

---

constant/index.js
model/index.js
model/track.js
package.json
routes/index.js
seeders/trackSeeder.js
src/tracks/__tests__/tracks.test.js
src/tracks/index.js
src/tracks/tracksController.js
src/tracks/tracksService.js

feat: fetch tracks from database

---

constant/index.js
model/index.js
model/schemas/index.js
model/tag.js
package-lock.json
package.json
routes/index.js
src/answers/__tests__/answer.test.js
src/answers/answersService.js
src/bookmarks/__tests__/bookmarks.test.js
src/comments/__tests__/comments.test.js
src/comments/commentsService.js
src/common/apiFeatures.js
src/posts/__tests__/posts.test.js
src/posts/postsController.js
src/posts/postsService.js
src/posts/postsValidator.js
src/questions/__tests__/questions.test.js
src/questions/questionsController.js
src/questions/questionsService.js
src/questions/questionsValidator.js
src/tags/__tests__/tags.test.js
src/tags/index.js
src/tags/tagsController.js
src/tags/tagsService.js
src/tags/tagsValidator.js

This PR...
- add API to fetch tags from the database
- create/update a post/question with tags
- search for posts/questions by tags
Fixes #109

feat: add support for Tags

---

src/common/apiFeatures.js

chore(api): Add metadata for non-paginated data to API response

---

src/bookmarks/bookmarksController.js
src/bookmarks/bookmarksService.js
src/bookmarks/bookmarksValidator.js
src/bookmarks/index.js

This PR...
- exposes an API to bulk-delete bookmarks
Fixes #219

feat(api): bulk delete bookmarks

---

src/answers/answersController.js
src/answers/answersService.js
src/bookmarks/bookmarksService.js
src/comments/commentsController.js
src/comments/commentsService.js
src/posts/postsController.js
src/posts/postsService.js
src/questions/questionsController.js
src/questions/questionsService.js

Add isBookmarked property to all query/mutation response objects for all content

---

constant/index.js
src/mailer/mailerService.js
src/mailer/templates/emailVerification.hbs
src/mailer/templates/passwordReset.hbs

feat: update email templates
